# Makefile for LaTeX documents. Heavily modified from
# <https://tex.stackexchange.com/a/40759>

##############################################################################
##                                  Config                                  ##
##############################################################################

# VARIABLES -- SET THESE!

# File names of all TeX files to be compiled into PDF files. The first one is
# considered the main file and is e.g. built by target 'main' and watched by
# target 'watch'.
TEX_FILES := main.tex \
             abstract_sa.tex \
             curriculum_scientiae_sa.tex \
             publications_sa.tex \
             selbststaendigkeitserklaerung_sa.tex

# Settings for creating an archive file using the 'dist' target. Contains all
# files in the current dir except for version control data, hidden files, and
# all files / dirs named in the DIST_EXCLUDE variable.
DIST_NAME      := phd_thesis
DIST_EXCLUDE   := **/old .nfs*

# Specify additional dirs in which latexmk -C is run for clean target.
CLEAN_DIRS     := frontmatter backmatter appendices chapters

# Pre-/suffixes of additonal files or dirs that (may) need to be removed.
CLEAN_PREFIXES :=
CLEAN_SUFFIXES := _vimtex_selected.synctex.gz \
                  _vimtex_selected.pdf
CLEAN_FILES    := *.html pdflatex*.fls

# Tools and flags.
LATEXMK        := latexmk
LATEXMK_FLAGS  := -bibtex \
                  -latexoption='-interaction=nonstopmode -synctex=1 -shell-escape'

# Version history and html file generation (only for template development).
PANDOC := pandoc
HISTORY_TEX_FILE := appendices/changes.tex


##############################################################################
##                                  Rules                                   ##
##############################################################################

# Remove .tex extension from main file name.
TEX_FILES_BASENAME := $(basename $(TEX_FILES))

# Include non-file targets in .PHONY so they are run regardless of any file of
# the given name existing.
.PHONY: all changes html clean watch watchall watch-%.tex FORCE tst

# Delete files when their creation failed. Prevents broken target files.
.DELETE_ON_ERROR:

# The first rule in a Makefile is the one executed by default ("make"). It
# should always be the "all" rule, so that "make" and "make all" are identical.
all: $(addsuffix .pdf, $(TEX_FILES_BASENAME))

# Main target to only build the main document.
main: $(word 1,$(TEX_FILES_BASENAME)).pdf

# In case you didn't know, '$@' is a variable holding the name of the target,
# and '$<' is a variable holding the (first) prerequisite of a rule.
# Symbol '%' is used for pattern rules and matches the rest of the file name.

# MAIN LATEXMK RULES
%.pdf: %.tex FORCE
	$(LATEXMK) -pdf -outdir='$(dir $<)' $(LATEXMK_FLAGS) '$<'

%.dvi: %.tex FORCE
	$(LATEXMK) -dvi -outdir='$(dir $<)' $(LATEXMK_FLAGS) '$<'


# Empty recipe. Recipes for targets specifying FORCE as prerequisite will
# always be executed. Similar to .PHONY targets, BUT .PHONY means that the
# target name is NOT a file which is not correct for the main TeX file. The
# FORCE target itself, however, should be PHONY to still work if there is a
# file called FORCE.
FORCE:


# Clean using latexmk's clean function after cleaning individual files.
clean: $(addprefix clean-, $(notdir $(TEX_FILES_BASENAME)))
	for dir in . $(CLEAN_DIRS); do \
	    ( cd "$$dir" && $(LATEXMK) -C ); \
	done
	rm -f $(CLEAN_FILES);


# Also clean up the remaining files manually in all specified directories.
# Cryptic variable removes 'clean-' prefix. Prefixes/suffixes are NOT escaped.
clean-%:
	for dir in . $(CLEAN_DIRS); do \
	( \
	    cd "$$dir"; \
	    for prefix in $(CLEAN_PREFIXES); do \
	        rm -rf $$prefix"$(@:clean-%=%)"; \
	    done; \
	    for suffix in $(CLEAN_SUFFIXES); do \
	        rm -rf "$(@:clean-%=%)"$$suffix; \
	    done; \
	); \
	done

# Use $(call autogen_msg,from_file,make_target) to display the message that
# the file was generated from file <from_file> by target <make_target>.
autogen_msg = echo '<!--'; \
              echo '    DO NOT EDIT THIS FILE MANUALLY!'; \
              echo '    It was generated automatically from file `$(1)` by `make $(2)`.'; \
              echo '-->';

changes: CHANGES.md

CHANGES.md: $(HISTORY_TEX_FILE)
	{ \
	    $(call autogen_msg,$<,changes) \
	    $(PANDOC) --from latex --to markdown '$<'; \
	} > '$@'

html: intro.html changes.html

intro.html: README.md
	{ \
	    $(call autogen_msg,$<,html) \
	    $(PANDOC) --from markdown --to html '$<'; \
	} > '$@'

changes.html: $(HISTORY_TEX_FILE)
	{ \
	    $(call autogen_msg,$<,html) \
	    $(PANDOC) --from latex --to html '$<' | \
	        sed -e 's/<h1 /<h2 /'; \
	} > '$@'

# Continuous compilation rules. Watches a selected TeX file for changes and
# recompiles it as soon as any is detected. Also monitors the file's
# dependencies like included files, bibliographies, graphics etc.
# Pattern rule, call it like so: make watch-my_document.tex
watch-%.tex: %.tex
	$(LATEXMK) -f -pvc -view=none -pdf -outdir='$(dir $<)' \
                $(LATEXMK_FLAGS) '$<'


# If no file is specified for watching, default to the first one from
# TEX_FILES (which is usually the main document).
watch: watch-$(word 1,$(TEX_FILES))


# Watches the entire directory and all subdirectories for changes, not just a
# selected selected file.  Requires external dependency inotify-tools.
MAKE_CMD = $(MAKE) all && echo 'Success.' || echo 'ERROR, see above.'
watchall:
	@[ -n "$$(command -v inotifywait)" ] || \
	    { echo 'inotifywait required but not found, try "make watch"'; exit 1; }
	-$(MAKE_CMD)            # dash means do not die on compilation errors
	@while true; do \
	    echo -n 'Monitoring files... '; \
	    FILE=$$(inotifywait -qre close_write . | sed -n 's/.*\s\(\w\)/\1/p'); \
	    echo "$$FILE"; \
	    sleep 0.2; \
	    $(MAKE_CMD) ; \
	done


dist_timestamp:
	@echo "$$( date -Iminutes )" > dist_timestamp

# Construct --exclude switches from DIST_EXCLUDE for tar. This breaks the
# syntax highlighting of vim.
EXCLUDE_ARGS := $(addprefix --exclude="./$$dir_name/, $(DIST_EXCLUDE))
EXCLUDE_ARGS := $(addsuffix ", $(EXCLUDE_ARGS))

# To exclude Makefile from tarball, add --exclude="./$$dir_name/Makefile"
dist: dist_timestamp clean
	@echo 'Creating tarball...'; \
	    current_path=`realpath .` ; \
	    dir_name=`basename $$current_path` ; \
	    dist_name='$(DIST_NAME)'; \
	    target="../$$dist_name.tar.gz" ; \
	    rm -f "$$target"; \
	    tar -C .. -czf "$$target" --exclude-vcs $(EXCLUDE_ARGS) \
	        --force-local --transform="s,$$dir_name,$$dist_name," \
	        "./$$dir_name" ; \
	    chmod a+r "$$target"; \
	    rm 'dist_timestamp'; \
	    echo "Successfully created distribution: '$$target'"; \


# EOF
